name: Commit CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install deps
        run: sudo apt-get update && sudo apt-get -y install meson libargparse-dev liblua5.4-dev libyaml-cpp-dev libboost-dev libboost-regex-dev
      - name: Build
        run: mkdir dist && meson setup build --prefer-static --prefix=$(realpath ./dist) --buildtype=release && ninja install -C build
      - name: Create nightly release
        if: ${{ github.repository == 'rimeinn/mira' && github.ref == 'refs/heads/master' }}
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Latest build"
          files: |
            dist/bin/mira
