name: Commit CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get -y install ninja-build libargparse-dev liblua5.4-dev librime-dev libyaml-cpp-dev
      - name: Build
        run: cmake -S. -Bbuild -GNinja -DCMAKE_INSTALL_PREFIX=./dist && cmake --build build && cmake --install build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mira-linux-x86_64
          path: |
            dist/**
      - name: Upload latest build
        if: ${{ github.repository == 'rimeinn/mira' && github.ref == 'refs/heads/master' }}
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Latest build"
          files: |
            dist/**

