name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install deps
        run: sudo apt-get update && sudo apt-get -y install meson libargparse-dev liblua5.4-dev libyaml-cpp-dev libboost-dev libboost-regex-dev
      - name: Build
        run: mkdir dist && meson setup build --prefer-static --prefix=$(realpath ./dist) --buildtype=release && ninja install -C build
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/bin/mira
          asset_name: mira-linux-x86_64
          asset_content_type: application/octet-stream
